import type { NextPage } from 'next';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {

  return (
    <form className={styles.form}>
      <section className={styles.note}>
        <input className={styles.note_title} type="text" id="note-title" placeholder="Title" />
        <section className={styles.note_content_actions}>

          {/* bold */}
          <button className={styles.btn}>
            <img className={styles.icon} src="/icons/bold.svg" alt="bold button icon" />
          </button>

          {/* italic */}
          <button className={styles.btn}>
            <img className={styles.icon} src="/icons/italic.svg" alt="italic button icon" />
          </button>

          {/* underline */}
          <button className={styles.btn}>
            <img className={styles.icon} src="/icons/underline.svg" alt="bold button icon" />
          </button>

          {/* strikethrough */}
          <button className={styles.btn}>
            <img className={styles.icon} src="/icons/strikethrough.svg" alt="strikethrough button icon" />
          </button>

          {/* quote */}
          <button className={styles.btn}>
            <img className={styles.icon} src="/icons/quote.svg" alt="quote button icon" />
          </button>

          {/* divider */}
          <button className={styles.btn}>
            <img className={styles.icon} src="/icons/divider.svg" alt="divider button icon" />
          </button>

          {/* code */}
          <button className={styles.btn}>
            <img className={styles.icon} src="/icons/code.svg" alt="code button icon" />
          </button>

          {/* bullets */}
          <button className={styles.btn}>
            <img className={styles.icon} src="/icons/bullets.svg" alt="bullets button icon" />
          </button>

          {/* numbers */}
          <button className={styles.btn}>
            <img className={styles.icon} src="/icons/numbers.svg" alt="numbers button icon" />
          </button>
        </section>
        <textarea className={styles.note_content} name="note content" cols={30} rows={10} placeholder="Your note" ></textarea>
      </section>
      <section className={styles.note_actions}>
        <select></select>

        <button className={styles.btn_publish}>Publish</button>
      </section>
    </form>
  )
};

// cols = "30" rows = "10"

// const Home: NextPage = () => {
//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       <main className={styles.main}>
//         <h1 className={styles.title}>
//           Welcome to <a href="https://nextjs.org">Next.js!</a>
//         </h1>

//         <p className={styles.description}>
//           Get started by editing{' '}
//           <code className={styles.code}>pages/index.tsx</code>
//         </p>

//         <div className={styles.grid}>
//           <a href="https://nextjs.org/docs" className={styles.card}>
//             <h2>Documentation &rarr;</h2>
//             <p>Find in-depth information about Next.js features and API.</p>
//           </a>

//           <a href="https://nextjs.org/learn" className={styles.card}>
//             <h2>Learn &rarr;</h2>
//             <p>Learn about Next.js in an interactive course with quizzes!</p>
//           </a>

//           <a
//             href="https://github.com/vercel/next.js/tree/canary/examples"
//             className={styles.card}
//           >
//             <h2>Examples &rarr;</h2>
//             <p>Discover and deploy boilerplate example Next.js projects.</p>
//           </a>

//           <a
//             href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//           >
//             <h2>Deploy &rarr;</h2>
//             <p>
//               Instantly deploy your Next.js site to a public URL with Vercel.
//             </p>
//           </a>
//         </div>
//       </main>

//       <footer className={styles.footer}>
//         <a
//           href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//           target="_blank"
//           rel="noopener noreferrer"
//         >
//           Powered by{' '}
//           <span className={styles.logo}>
//             <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
//           </span>
//         </a>
//       </footer>
//     </div>
//   )
// }

export default Home
